### ISSUE TITLE
apt unable to find i386 packages -- specify amd64 in sources.list?

### ISSUE THREAD

**Issue by m4lvin** [alanfranz/atom-text-editor-repository#11]
First, thanks for running this repository!

On Debian stretch (with multiarch enabled) since yesterday I get this error on `apt update`:

> E: Failed to fetch https://dl.bintray.com/alanfranz/atom-apt/dists/stable/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

But from `atom_stable_retrieve.py` I understand you only provide amd64 packages anyway? So I don't get why apt searches for an i386/Packages file. Changing the sources.list line from

    deb https://dl.bintray.com/alanfranz/atom-apt stable main

to

    deb [arch=amd64] https://dl.bintray.com/alanfranz/atom-apt stable main

fixes this. But this was not necessary before. Maybe there is some configuration on bintray to specify the architecture?

**Comment by alanfranz** [comment]
this looks like a multiarch issue:

https://wiki.debian.org/Multiarch/HOWTO

It seems that by default apt with multiarch tries downloading data for all architectures.

There's just a 64 bit repo because there's no 32 bit upstream release of atom. But the issues is specific to multiarch, and may happen with any package that has no 32 bit counterpart. I'll clarify that 32bit is unsupported, btw.
